version: '3.8'

services:
  minio:
    image: bitnami/minio:latest
    container_name: nexblog-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER_SESSION_DURATION: 7d
      MINIO_BROWSER_LOGIN_ANIMATION: off
    volumes:
      - minio_data:/bitnami/minio/data
    command: server /bitnami/minio/data --console-address ":9001"

volumes:
  minio_data: 