[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/minio/health/live"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "server /data --console-address :9001"

[[services]]
environment = [
  "MINIO_ROOT_USER=${MINIO_ROOT_USER}",
  "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}",
  "MINIO_BROWSER_SESSION_DURATION=7d",
]
image = "bitnami/minio:latest"
name = "minio"
volumes = ["/data"]
